IF DB_ID(N'AIStudyHub') IS NULL
BEGIN
  CREATE DATABASE AIStudyHub;
END;
GO

USE AIStudyHub;
GO

IF OBJECT_ID(N'dbo.USER_MANAGEMENT', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.USER_MANAGEMENT (
    id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(120) NOT NULL,
    email NVARCHAR(255) NOT NULL UNIQUE,
    role NVARCHAR(20) NOT NULL DEFAULT 'User',
    plan_name NVARCHAR(20) NOT NULL DEFAULT 'Basic',
    folders INT NOT NULL DEFAULT 0,
    tests INT NOT NULL DEFAULT 0,
    type NVARCHAR(20) NOT NULL DEFAULT 'initials',
    initials NVARCHAR(10) NOT NULL DEFAULT '?',
    color NVARCHAR(20) NOT NULL DEFAULT '#DBEAFE',
    text_color NVARCHAR(20) NOT NULL DEFAULT '#1D4ED8',
    location NVARCHAR(120) NOT NULL DEFAULT 'Not set',
    last_login NVARCHAR(80) NOT NULL DEFAULT 'Never',
    latest_action NVARCHAR(500) NOT NULL DEFAULT 'No activity yet.',
    action_time NVARCHAR(80) NOT NULL DEFAULT 'Just now',
    status NVARCHAR(20) NOT NULL DEFAULT 'Active',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.LIBRARY_MANAGEMENT_SEMESTERS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.LIBRARY_MANAGEMENT_SEMESTERS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(120) NOT NULL UNIQUE,
    start_date NVARCHAR(30) NOT NULL DEFAULT '',
    end_date NVARCHAR(30) NOT NULL DEFAULT '',
    description NVARCHAR(600) NOT NULL DEFAULT '',
    status NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    storage NVARCHAR(40) NOT NULL DEFAULT '0 MB',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.LIBRARY_MANAGEMENT_COURSES', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.LIBRARY_MANAGEMENT_COURSES (
    id INT IDENTITY(1,1) PRIMARY KEY,
    semester_id INT NOT NULL,
    name NVARCHAR(160) NOT NULL,
    code NVARCHAR(40) NOT NULL,
    instructor NVARCHAR(120) NOT NULL DEFAULT '',
    docs INT NOT NULL DEFAULT 0,
    updated_label NVARCHAR(80) NOT NULL DEFAULT 'Just now',
    status NVARCHAR(20) NOT NULL DEFAULT 'Active',
    icon NVARCHAR(30) NOT NULL DEFAULT 'book',
    color NVARCHAR(20) NOT NULL DEFAULT '#d1fae5',
    icon_color NVARCHAR(20) NOT NULL DEFAULT '#059669',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_library_courses_semesters
      FOREIGN KEY (semester_id) REFERENCES dbo.LIBRARY_MANAGEMENT_SEMESTERS(id) ON DELETE CASCADE
  );
END;
GO

IF OBJECT_ID(N'dbo.PRACTICE_TEST_MANAGEMENT', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.PRACTICE_TEST_MANAGEMENT (
    id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(180) NOT NULL UNIQUE,
    docs INT NOT NULL DEFAULT 0,
    questions INT NOT NULL DEFAULT 0,
    subject NVARCHAR(120) NOT NULL DEFAULT 'General',
    creator_initials NVARCHAR(10) NOT NULL DEFAULT '??',
    creator_name NVARCHAR(120) NOT NULL DEFAULT 'Unknown',
    creator_color NVARCHAR(20) NOT NULL DEFAULT '#DBEAFE',
    creator_text NVARCHAR(20) NOT NULL DEFAULT '#1D4ED8',
    attempts INT NOT NULL DEFAULT 0,
    avg INT NOT NULL DEFAULT 0,
    status NVARCHAR(30) NOT NULL DEFAULT 'Pending Review',
    created_type NVARCHAR(30) NOT NULL DEFAULT 'AI Generated',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.PRACTICE_TEST_MANAGEMENT_QUESTIONS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.PRACTICE_TEST_MANAGEMENT_QUESTIONS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    test_id INT NOT NULL,
    question NVARCHAR(1000) NOT NULL,
    question_type NVARCHAR(40) NOT NULL DEFAULT 'Multiple Choice',
    difficulty NVARCHAR(20) NOT NULL DEFAULT 'Medium',
    ai_score INT NOT NULL DEFAULT 0,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_practice_questions_tests
      FOREIGN KEY (test_id) REFERENCES dbo.PRACTICE_TEST_MANAGEMENT(id) ON DELETE CASCADE
  );
END;
GO

IF OBJECT_ID(N'dbo.PRACTICE_TEST_MANAGEMENT_REVIEW_QUEUE', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.PRACTICE_TEST_MANAGEMENT_REVIEW_QUEUE (
    id INT IDENTITY(1,1) PRIMARY KEY,
    queue_id NVARCHAR(40) NOT NULL UNIQUE,
    course NVARCHAR(160) NOT NULL DEFAULT '',
    time_label NVARCHAR(80) NOT NULL DEFAULT 'Just now',
    flag NVARCHAR(80) NOT NULL DEFAULT '',
    flag_score INT NULL,
    question NVARCHAR(1000) NOT NULL,
    ai_answer NVARCHAR(1000) NOT NULL DEFAULT '',
    current_answer NVARCHAR(1000) NOT NULL DEFAULT '',
    flag_note NVARCHAR(1000) NOT NULL DEFAULT '',
    user_report_student NVARCHAR(120) NOT NULL DEFAULT '',
    user_report_text NVARCHAR(1000) NOT NULL DEFAULT '',
    queue_type NVARCHAR(20) NOT NULL DEFAULT 'low',
    status NVARCHAR(20) NOT NULL DEFAULT 'Pending',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.DOCUMENT_MANAGEMENT', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.DOCUMENT_MANAGEMENT (
    id INT IDENTITY(1,1) PRIMARY KEY,
    title NVARCHAR(255) NOT NULL UNIQUE,
    document_type NVARCHAR(20) NOT NULL DEFAULT 'PDF',
    size_label NVARCHAR(40) NOT NULL DEFAULT '0 MB',
    size_mb DECIMAL(10,2) NOT NULL DEFAULT 0,
    course NVARCHAR(160) NOT NULL DEFAULT '',
    semester NVARCHAR(120) NOT NULL DEFAULT '',
    uploader_name NVARCHAR(120) NOT NULL DEFAULT 'Unknown',
    uploader_initials NVARCHAR(10) NOT NULL DEFAULT '??',
    uploader_color NVARCHAR(20) NOT NULL DEFAULT '#DBEAFE',
    uploader_text NVARCHAR(20) NOT NULL DEFAULT '#1D4ED8',
    uploaded_at_label NVARCHAR(80) NOT NULL DEFAULT 'Just now',
    status NVARCHAR(20) NOT NULL DEFAULT 'Pending',
    description NVARCHAR(1000) NOT NULL DEFAULT '',
    reject_reason NVARCHAR(1000) NOT NULL DEFAULT '',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.PAYMENT_MANAGEMENT', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.PAYMENT_MANAGEMENT (
    id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(120) NOT NULL,
    email NVARCHAR(255) NOT NULL UNIQUE,
    avatar_url NVARCHAR(500) NOT NULL DEFAULT '',
    initials NVARCHAR(10) NOT NULL DEFAULT '??',
    avatar_bg NVARCHAR(20) NOT NULL DEFAULT '#dbeafe',
    avatar_color NVARCHAR(20) NOT NULL DEFAULT '#1d4ed8',
    plan_name NVARCHAR(20) NOT NULL DEFAULT 'PLUS',
    status NVARCHAR(20) NOT NULL DEFAULT 'Active',
    billing NVARCHAR(20) NOT NULL DEFAULT 'Monthly',
    payment_date_label NVARCHAR(80) NOT NULL DEFAULT 'Just now',
    amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.PAYMENT_MANAGEMENT_PLANS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.PAYMENT_MANAGEMENT_PLANS (
    plan_code NVARCHAR(20) NOT NULL PRIMARY KEY,
    price DECIMAL(10,2) NOT NULL DEFAULT 0,
    billing NVARCHAR(20) NOT NULL DEFAULT 'Monthly',
    description NVARCHAR(300) NOT NULL DEFAULT '',
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO
