import { useState } from 'react';
import { Link } from 'react-router-dom';
import Button from '../../components/common/Button';
import rocketLaptop from '../../assets/landingImages/rocket_laptop.png';


function GuidePage() {
  const [openFaq, setOpenFaq] = useState(null);

  const faqs = [
    {
      question: 'Does FSTUDY support multiple languages?',
      answer: 'Yes! FSTUDY supports multiple languages including Vietnamese, English, Japanese, and Korean. You can upload documents in any of these languages and chat with the AI tutor seamlessly.'
    },
    {
      question: 'How many documents can I upload on the free plan?',
      answer: 'On the Basic (Free) plan, you can upload up to 3 documents per month. Upgrading to the Premium or Pro plan provides unlimited document analysis and larger cloud storage limits.'
    },
    {
      question: 'Can I export my AI conversations?',
      answer: 'Absolutely! All chat logs and summaries generated by the AI tutor can be easily exported as Markdown, PDF, or txt files directly from your workspace panel.'
    }
  ];

  const toggleFaq = (index) => {
    if (openFaq === index) {
      setOpenFaq(null);
    } else {
      setOpenFaq(index);
    }
  };

  return (
    <div className="guide-section">
      {/* Header */}
      <div className="guide-header">
        <h1 className="guide-title">How can we help you today?</h1>
        <p className="guide-sub">
          Explore our comprehensive guides and documentation to master FSTUDY and supercharge your learning journey.
        </p>
      </div>

      {/* Row 1 Grid: Getting Started & AI Chatbot Tips */}
      <div className="guide-grid" style={{ marginBottom: '24px' }}>
        {/* Card 1: Getting Started */}
        <div className="landing-feature-card" style={{ display: 'flex', flexDirection: 'column' }}>
          <div className="landing-feature-icon-box purple">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <path d="M18 3a3 3 0 0 0-3-3H9a3 3 0 0 0-3 3v12a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V3z"/>
              <path d="M6 6H4a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-8a2 2 0 0 0-2-2h-2"/>
            </svg>
          </div>
          <h3 className="landing-feature-title">Getting Started</h3>
          <div className="guide-card-list">
            <div className="guide-card-item">
              <span className="guide-card-bullet" />
              <span>Creating your first AI-assisted workspace</span>
            </div>
            <div className="guide-card-item">
              <span className="guide-card-bullet" />
              <span>Connecting your academic accounts</span>
            </div>
            <div className="guide-card-item">
              <span className="guide-card-bullet" />
              <span>Touring the FSTUDY dashboard</span>
            </div>
          </div>
          <div style={{ marginTop: 'auto', paddingTop: '20px', borderRadius: '12px', overflow: 'hidden' }}>
            <img src={rocketLaptop} alt="Laptop launching rocket illustration" style={{ width: '100%', height: 'auto', maxHeight: '180px', objectFit: 'contain', display: 'block', margin: '0 auto' }} />
          </div>
        </div>

        {/* Card 2: AI Chatbot Tips (Premium styled) */}
        <div className="landing-feature-card" style={{ background: 'var(--color-primary)', color: '#ffffff', border: 'none' }}>
          <div className="landing-feature-icon-box" style={{ background: 'rgba(255,255,255,0.15)', color: '#ffffff' }}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
            </svg>
          </div>
          <h3 className="landing-feature-title" style={{ color: '#ffffff' }}>AI Chatbot Tips</h3>
          <div className="guide-card-list">
            <div className="guide-card-item" style={{ color: 'rgba(255,255,255,0.9)' }}>
              <span className="guide-card-bullet" style={{ backgroundColor: '#ffffff' }} />
              <span>Prompting for deep analysis</span>
            </div>
            <div className="guide-card-item" style={{ color: 'rgba(255,255,255,0.9)' }}>
              <span className="guide-card-bullet" style={{ backgroundColor: '#ffffff' }} />
              <span>Summarizing 30+ page docs</span>
            </div>
            <div className="guide-card-item" style={{ color: 'rgba(255,255,255,0.9)' }}>
              <span className="guide-card-bullet" style={{ backgroundColor: '#ffffff' }} />
              <span>Citing sources with AI</span>
            </div>
          </div>
          <button type="button" className="guide-playbook-link" onClick={() => alert('Opening Playbook PDF...')} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}>
            View Playbook <span>&rarr;</span>
          </button>
        </div>
      </div>

      {/* Row 2 Grid: Document Management & Security & Privacy */}
      <div className="guide-grid-alt">
        {/* Card 3: Document Management */}
        <div className="landing-feature-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
            <div className="landing-feature-icon-box blue" style={{ marginBottom: 0 }}>
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/>
              </svg>
            </div>
            <span className="guide-new-update-badge">New Update</span>
          </div>
          <h3 className="landing-feature-title">Document Management</h3>
          <div className="guide-doc-grid">
            <div className="guide-doc-item">
              <h4 className="guide-doc-item-title">Bulk Upload Guide</h4>
              <p className="guide-doc-item-desc">PDF, DOCX, and more</p>
            </div>
            <div className="guide-doc-item">
              <h4 className="guide-doc-item-title">Smart OCR Scan</h4>
              <p className="guide-doc-item-desc">Digitize handwritten notes</p>
            </div>
            <div className="guide-doc-item">
              <h4 className="guide-doc-item-title">Cloud Sync</h4>
              <p className="guide-doc-item-desc">Drive & Dropbox setup</p>
            </div>
            <div className="guide-doc-item">
              <h4 className="guide-doc-item-title">Version Control</h4>
              <p className="guide-doc-item-desc">History and recovery</p>
            </div>
          </div>
        </div>

        {/* Card 4: Security & Privacy */}
        <div className="landing-feature-card">
          <div className="landing-feature-icon-box green">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
            </svg>
          </div>
          <h3 className="landing-feature-title">Security & Privacy</h3>
          <p className="landing-feature-desc" style={{ marginBottom: 0 }}>
            Your data is encrypted and never used to train global AI models. Learn how we protect your academic integrity.
          </p>
          <div className="guide-sec-grid">
            <div className="guide-sec-item">
              <span className="guide-sec-icon">✓</span>
              <span>256-bit Encryption</span>
            </div>
            <div className="guide-sec-item">
              <span className="guide-sec-icon">✓</span>
              <span>Data Residency</span>
            </div>
            <div className="guide-sec-item">
              <span className="guide-sec-icon">✓</span>
              <span>SOC2 Compliance</span>
            </div>
            <div className="guide-sec-item">
              <span className="guide-sec-icon">✓</span>
              <span>Private AI Nodes</span>
            </div>
          </div>
          <button type="button" className="guide-trust-link" style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, width: 'fit-content' }} onClick={() => alert('Loading Trust Report...')} >
            Read our Trust Report <span>&rarr;</span>
          </button>
        </div>
      </div>

      {/* ── FAQ Accordion Section ── */}
      <section className="faq-section">
        <div className="faq-header-row">
          <div>
            <h2 className="faq-section-title">Frequently Asked Questions</h2>
            <p className="faq-section-sub">Quick answers to common questions from the community.</p>
          </div>
          <button className="faq-btn-view-all" type="button" onClick={() => alert('Redirecting to Full Help Center...')}>
            View All FAQ
          </button>
        </div>

        <div className="faq-accordion">
          {faqs.map((faq, index) => {
            const isActive = openFaq === index;
            return (
              <div
                key={index}
                className={['faq-item', isActive ? 'active' : ''].join(' ').trim()}
                onClick={() => toggleFaq(index)}
              >
                <div className="faq-question-row">
                  <h4 className="faq-question">{faq.question}</h4>
                  <span className="faq-toggle-icon">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                      <line x1="12" y1="5" x2="12" y2="19"/>
                      <line x1="5" y1="12" x2="19" y2="12"/>
                    </svg>
                  </span>
                </div>
                {isActive && (
                  <p className="faq-answer">{faq.answer}</p>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* ── Support Banner ── */}
      <div className="landing-cta-banner">
        <h2 className="landing-cta-title">Can't find what you're looking for?</h2>
        <p className="landing-cta-sub">
          Our support team is available 24/7 to help you with any technical issues or feature requests.
        </p>
        <div className="landing-cta-actions">
          <button className="landing-btn-cta-white" type="button" onClick={() => alert('Support ticket form loading...')}>
            Contact Support
          </button>
          <button className="landing-btn-cta-outline" type="button" onClick={() => window.open('https://discord.gg', '_blank')}>
            Join Discord Community
          </button>
        </div>
      </div>
    </div>
  );
}

export default GuidePage;
