# Server
server.port=8080

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=PIEDTEAM;databaseName=AI_StudyHub;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Supabase
supabase.url=https://tutiziokwsmkmyqvdbls.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1dGl6aW9rd3Nta215cXZkYmxzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTcyMjc2OCwiZXhwIjoyMDk3Mjk4NzY4fQ.99gJdRGgr2JLHxanww8D5YtN70gOKLd76o0JNe5lNvE
supabase.bucket=documents